# This file was generated by GoReleaser. DO NOT EDIT.
cask "charter" do
  version "0.3.8"

  on_macos do
    on_intel do
      sha256 "31b957e14929573ec5afb87193035da01e08e4b2b107b0c9145d733acfb5df69"
      url "https://github.com/helloodokai/charter/releases/download/v#{version}/charter_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "03035d749931a99b81034b815ade21091059276970002de7e538074e8c528569"
      url "https://github.com/helloodokai/charter/releases/download/v#{version}/charter_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "29d21874e1b1a47f8e950386116a00e4758f1f016b540a70eea3c1297b66b26c"
      url "https://github.com/helloodokai/charter/releases/download/v#{version}/charter_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ebb238bbad2276a12f48283d4837d588f0774d539260a8e44655a5e04469bba9"
      url "https://github.com/helloodokai/charter/releases/download/v#{version}/charter_linux_arm64.tar.gz"
    end
  end

  name "charter"
  desc "Turn fuzzy intent into hardened, machine-readable specifications"
  homepage "https://github.com/helloodokai/charter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "charter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/charter"]
    end
  end

  # No zap stanza required

end
