# This file was generated by GoReleaser. DO NOT EDIT.
cask "charter" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "60df3a0d5caf9d68264e56ba46fec0038b83791a1fdb22cb6bf9f48d26824d96"
      url "https://github.com/helloodokai/charter/releases/download/v#{version}/charter_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "59169e45a2efd27bab222092744a6ee3ec3e360db2d2806518135702000a9fa4"
      url "https://github.com/helloodokai/charter/releases/download/v#{version}/charter_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6615ca7a60d4df54b3b454dc72607feac91142d423025864d82618fa0bf84e8d"
      url "https://github.com/helloodokai/charter/releases/download/v#{version}/charter_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9fa7f9ff9608781543771a1be4713f76a3431c155f27d26194ec1e7e5760f931"
      url "https://github.com/helloodokai/charter/releases/download/v#{version}/charter_linux_arm64.tar.gz"
    end
  end

  name "charter"
  desc "Turn fuzzy intent into hardened, machine-readable specifications"
  homepage "https://github.com/helloodokai/charter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "charter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/charter"]
    end
  end

  # No zap stanza required

end
