# This file was generated by GoReleaser. DO NOT EDIT.
cask "charter" do
  version "0.3.6"

  on_macos do
    on_intel do
      sha256 "2cc29042f70a875f6cb20362fd21abdfcb251fde208087fb9b00200e69f4235d"
      url "https://github.com/helloodokai/charter/releases/download/v#{version}/charter_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "03537df88d105a69ee6313ce80cbecd60effaa10c63fd8bf3d36659afc13f97f"
      url "https://github.com/helloodokai/charter/releases/download/v#{version}/charter_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "af1363edc99c541e1fd733f5b453767e24ab84c2ac09c39f6a4eb4f7727d72a7"
      url "https://github.com/helloodokai/charter/releases/download/v#{version}/charter_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "cbb5317a25ff7a3214e9023fdbb1f8088e20de28caae19f336369fcdcb920282"
      url "https://github.com/helloodokai/charter/releases/download/v#{version}/charter_linux_arm64.tar.gz"
    end
  end

  name "charter"
  desc "Turn fuzzy intent into hardened, machine-readable specifications"
  homepage "https://github.com/helloodokai/charter"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "charter"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/charter"]
    end
  end

  # No zap stanza required

end
